[[override]]
  name = "github.com/docker/cli"
  branch = "19.03"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "github.com/docker/cli"
    non-go = false